# Generated by Django 3.2.7 on 2022-12-31 01:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20211002_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackerapplication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hackerapplication',
            name='lennyface',
        ),
        migrations.RemoveField(
            model_name='hackerapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='lennyface',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='lennyface',
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='question_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='question_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='question_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2023),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2023),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'MakeMIT 2016'), (1, 'MakeMIT 2017'), (2, 'MakeMIT 2018'), (3, 'MakeMIT 2019')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2023),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'MakeMIT 2016'), (1, 'MakeMIT 2017'), (2, 'MakeMIT 2018'), (3, 'MakeMIT 2019')], max_length=7, null=True),
        ),
    ]
